import { PropsWithChildren } from "react";
import "../styles/globals.css";
import "bootstrap/dist/css/bootstrap.css";
import { PeopleList } from "./people-list";

export const metadata = {
	title: "Family Tree",
	description: "Generated by create next app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function (props: PropsWithChildren) {
	return (
		<html lang="en">
			<body>
				<div className="container-fluid">
					<div className="row">
						<div className="col-3">
							<h1>Menu</h1>
							<PeopleList />
						</div>
						<div className="col-9">{props.children}</div>
					</div>
				</div>
			</body>
		</html>
	);
}
