import { PropsWithChildren } from "react";
import "../styles/globals.css";
import "bootstrap/dist/css/bootstrap.css";
import { PeopleList } from "./people-list";
import { LoginGuard, MainHeader } from "./header";
import { SearchContextProvider } from "./search-context";

export const metadata = {
	title: "Family Tree",
	description: "Generated by create next app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout(props: PropsWithChildren) {
	return (
		<html lang="en" data-bs-theme="light">
			<body>
				<SearchContextProvider>
					<MainHeader />
					<div className="container-fluid">
						<LoginGuard>
							<div className="row">
								<PeopleList />
								<div className="col-12 col-md-9">{props.children}</div>
							</div>
						</LoginGuard>
					</div>
				</SearchContextProvider>
			</body>
		</html>
	);
}
