import { PropsWithChildren } from "react";
import "../styles/globals.css";
import "bootstrap/dist/css/bootstrap.css";
import { PeopleList } from "./people-list";
import { LoginGuard, MainHeader } from "./header";
import { SearchContextProvider } from "./search-context";

export const metadata = {
	title: "Family Tree",
	description: "Generated by create next app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout(props: PropsWithChildren) {
	return (
		<html lang="en">
			<body>
				<div className="container-fluid">
					<SearchContextProvider>
						<MainHeader />
						<LoginGuard>
							<div className="row">
								<div className="col-3">
									<h1>Menu</h1>
									<PeopleList />
								</div>
								<div className="col-9">{props.children}</div>
							</div>
						</LoginGuard>
					</SearchContextProvider>
				</div>
			</body>
		</html>
	);
}
