import type {NextPage} from "next";
import Head from "next/head";
import {FamilytreeLoader} from "../components/familytree";

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Family Tree</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <FamilytreeLoader/>
      </main>
    </div>
  );
};

export default Home;
